# Generated by Django 3.1 on 2020-12-16 15:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('from_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('url_picture', models.URLField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['from_date'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price_min', models.CharField(blank=True, max_length=100, null=True)),
                ('price_max', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('latlon', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('popular_times', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('url_picture', models.URLField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='trips.day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='trips.trip')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
    ]
