# Generated by Django 3.1 on 2020-12-14 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('url_picture', models.URLField(blank=True, null=True)),
                ('members', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField()),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_times', models.URLField(blank=True, null=True)),
                ('url_picture', models.URLField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='trips.day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
    ]
