# Generated by Django 3.1 on 2020-12-16 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
