# Generated by Django 3.1 on 2020-12-17 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20201216_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
