# Generated by Django 3.1 on 2020-12-16 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20201215_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['from_date']},
        ),
        migrations.AddField(
            model_name='day',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
