# Generated by Django 3.1 on 2020-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20201216_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='plan',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
