# Generated by Django 3.1 on 2020-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_plan_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Gastronomy', 'Gastronomy'), ('Walk', 'Walk'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
