# Generated by Django 3.1 on 2020-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20201216_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.FloatField(),
        ),
    ]
