# Generated by Django 3.1 on 2020-12-16 13:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20201216_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
