# Generated by Django 3.1 on 2020-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_plan_latlon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
